[package]
name = "ccallbacks"
version = "0.1.0"
authors = ["Satoshi Yoshikawa <yoshikawa@fairydevices.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.60"

[dependencies]
libc = "0.2.77"
